runtime: nodejs20

instance_class: F1

env_variables:
  NODE_ENV: production
  EMAIL_USER: songdh418@gmail.com
  EMAIL_PASS: ubggrywvrykvyybl
  TELEGRAM_BOT_TOKEN: "8862571434:AAHGPJKf7HCXzLFv_EvCXAnNUza412zjW2M"
  TELEGRAM_CHAT_ID: "8861091285"

handlers:
  - url: /.*
    script: auto
    secure: always

automatic_scaling:
  min_instances: 0
  max_instances: 1
  target_cpu_utilization: 0.65
