runtime: nodejs20

instance_class: F1

env_variables:
  NODE_ENV: production
  EMAIL_USER: songdh418@gmail.com
  EMAIL_PASS: ubggrywvrykvyybl
  TELEGRAM_BOT_TOKEN: "your_bot_token_here"
  TELEGRAM_CHAT_ID: "your_chat_id_here"

handlers:
  - url: /.*
    script: auto
    secure: always

automatic_scaling:
  min_instances: 0
  max_instances: 1
  target_cpu_utilization: 0.65
